-- ============================================
-- E-COMMERCE SALES & CUSTOMER ANALYTICS
-- SQL QUERIES
-- ============================================

-- ============================================
-- BASIC & MEDIUM QUERIES
-- Q1 - Q25
-- ============================================


-- Q1. Display all customers
SELECT *
FROM customers;


-- Q2. Display all products
SELECT *
FROM products;


-- Q3. Display all products with price greater than 5000
SELECT *
FROM products
WHERE price > 5000;


-- Q4. Display customers from Bangalore
SELECT *
FROM customers
WHERE city = 'Bangalore';


-- Q5. Display products belonging to Electronics category
SELECT p.product_name,
       p.price
FROM products p
JOIN categories c
    ON p.category_id = c.category_id
WHERE c.category_name = 'Electronics';


-- Q6. Display products priced between 1000 and 10000
SELECT *
FROM products
WHERE price BETWEEN 1000 AND 10000;


-- Q7. Display customers from Bangalore, Mumbai, or Delhi
SELECT *
FROM customers
WHERE city IN ('Bangalore', 'Mumbai', 'Delhi');


-- Q8. Display products whose name contains 'Book'
SELECT *
FROM products
WHERE product_name LIKE '%Book%';


-- Q9. Find the total number of customers
SELECT COUNT(*) AS total_customers
FROM customers;


-- Q10. Find the total number of products
SELECT COUNT(*) AS total_products
FROM products;


-- Q11. Find the average product price
SELECT AVG(price) AS average_price
FROM products;


-- Q12. Find the highest product price
SELECT MAX(price) AS highest_price
FROM products;


-- Q13. Find the lowest product price
SELECT MIN(price) AS lowest_price
FROM products;


-- Q14. Find the total number of orders
SELECT COUNT(*) AS total_orders
FROM orders;


-- Q15. Count orders based on their status
SELECT status,
       COUNT(*) AS total_orders
FROM orders
GROUP BY status;


-- Q16. Find the number of customers in each city
SELECT city,
       COUNT(*) AS customer_count
FROM customers
GROUP BY city;


-- Q17. Find the average product price in each category
SELECT c.category_name,
       AVG(p.price) AS average_price
FROM categories c
JOIN products p
    ON c.category_id = p.category_id
GROUP BY c.category_name;


-- Q18. Find the number of products in each category
SELECT c.category_name,
       COUNT(p.product_id) AS product_count
FROM categories c
LEFT JOIN products p
    ON c.category_id = p.category_id
GROUP BY c.category_name;


-- Q19. Find categories having more than 2 products
SELECT c.category_name,
       COUNT(p.product_id) AS product_count
FROM categories c
JOIN products p
    ON c.category_id = p.category_id
GROUP BY c.category_name
HAVING COUNT(p.product_id) > 2;


-- Q20. Display all orders with customer names
SELECT o.order_id,
       c.customer_name,
       o.order_date,
       o.status
FROM orders o
JOIN customers c
    ON o.customer_id = c.customer_id;


-- Q21. Display completed orders with customer names
SELECT o.order_id,
       c.customer_name,
       o.order_date
FROM orders o
JOIN customers c
    ON o.customer_id = c.customer_id
WHERE o.status = 'Completed';


-- Q22. Find the total number of orders placed by each customer
SELECT c.customer_id,
       c.customer_name,
       COUNT(o.order_id) AS total_orders
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id,
         c.customer_name;


-- Q23. Find customers who have not placed any orders
SELECT c.customer_id,
       c.customer_name
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id
WHERE o.order_id IS NULL;


-- Q24. Find the total quantity of products sold
SELECT SUM(quantity) AS total_quantity_sold
FROM order_items;


-- Q25. Find the total revenue generated
SELECT SUM(p.price * oi.quantity) AS total_revenue
FROM order_items oi
JOIN products p
    ON oi.product_id = p.product_id;

-- ============================================
-- JOINS, GROUP BY & SUBQUERIES
-- Q26 - Q50
-- ============================================

-- Q26. Display product names with their category names
SELECT p.product_name,
       c.category_name
FROM products p
JOIN categories c
    ON p.category_id = c.category_id;


-- Q27. Display customer names and their orders
SELECT c.customer_name,
       o.order_id,
       o.order_date,
       o.status
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id;


-- Q28. Display order details with customer and product names
SELECT o.order_id,
       c.customer_name,
       p.product_name,
       oi.quantity
FROM orders o
JOIN customers c
    ON o.customer_id = c.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id;


-- Q29. Calculate revenue for each order
SELECT o.order_id,
       SUM(p.price * oi.quantity) AS order_revenue
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id
GROUP BY o.order_id;


-- Q30. Calculate revenue generated by each customer
SELECT c.customer_id,
       c.customer_name,
       SUM(p.price * oi.quantity) AS total_revenue
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id
GROUP BY c.customer_id,
         c.customer_name;


-- Q31. Calculate revenue generated by each product
SELECT p.product_id,
       p.product_name,
       SUM(p.price * oi.quantity) AS total_revenue
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY p.product_id,
         p.product_name;


-- Q32. Calculate total quantity sold for each product
SELECT p.product_id,
       p.product_name,
       SUM(oi.quantity) AS total_quantity
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY p.product_id,
         p.product_name;


-- Q33. Find products that have never been ordered
SELECT p.product_id,
       p.product_name
FROM products p
LEFT JOIN order_items oi
    ON p.product_id = oi.product_id
WHERE oi.product_id IS NULL;


-- Q34. Find customers who have placed at least one order
SELECT DISTINCT c.customer_id,
       c.customer_name
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id;


-- Q35. Find customers who placed more than one order
SELECT c.customer_id,
       c.customer_name,
       COUNT(o.order_id) AS total_orders
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id,
         c.customer_name
HAVING COUNT(o.order_id) > 1;


-- Q36. Find the customer with the highest total revenue
SELECT c.customer_id,
       c.customer_name,
       SUM(p.price * oi.quantity) AS total_revenue
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id
GROUP BY c.customer_id,
         c.customer_name
ORDER BY total_revenue DESC
FETCH FIRST 1 ROW ONLY;


-- Q37. Find the most expensive product
SELECT product_id,
       product_name,
       price
FROM products
WHERE price = (
    SELECT MAX(price)
    FROM products
);


-- Q38. Find products whose price is greater than the average product price
SELECT product_id,
       product_name,
       price
FROM products
WHERE price > (
    SELECT AVG(price)
    FROM products
);


-- Q39. Find customers whose total revenue is greater than 50000
SELECT c.customer_id,
       c.customer_name,
       SUM(p.price * oi.quantity) AS total_revenue
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id
GROUP BY c.customer_id,
         c.customer_name
HAVING SUM(p.price * oi.quantity) > 50000;


-- Q40. Find the category with the highest average product price
SELECT c.category_name,
       AVG(p.price) AS average_price
FROM categories c
JOIN products p
    ON c.category_id = p.category_id
GROUP BY c.category_name
ORDER BY average_price DESC
FETCH FIRST 1 ROW ONLY;


-- Q41. Find the total revenue for each category
SELECT c.category_name,
       SUM(p.price * oi.quantity) AS category_revenue
FROM categories c
JOIN products p
    ON c.category_id = p.category_id
JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY c.category_name;


-- Q42. Find categories generating revenue greater than 20000
SELECT c.category_name,
       SUM(p.price * oi.quantity) AS category_revenue
FROM categories c
JOIN products p
    ON c.category_id = p.category_id
JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY c.category_name
HAVING SUM(p.price * oi.quantity) > 20000;


-- Q43. Find the number of orders placed by each city
SELECT c.city,
       COUNT(o.order_id) AS total_orders
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.city;


-- Q44. Find the total revenue generated by each city
SELECT c.city,
       SUM(p.price * oi.quantity) AS total_revenue
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id
GROUP BY c.city;


-- Q45. Find the average order value
SELECT AVG(order_revenue) AS average_order_value
FROM (
    SELECT o.order_id,
           SUM(p.price * oi.quantity) AS order_revenue
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    JOIN products p
        ON oi.product_id = p.product_id
    GROUP BY o.order_id
);


-- Q46. Find orders whose revenue is greater than the average order value
SELECT order_id,
       order_revenue
FROM (
    SELECT o.order_id,
           SUM(p.price * oi.quantity) AS order_revenue
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    JOIN products p
        ON oi.product_id = p.product_id
    GROUP BY o.order_id
)
WHERE order_revenue > (
    SELECT AVG(order_revenue)
    FROM (
        SELECT o.order_id,
               SUM(p.price * oi.quantity) AS order_revenue
        FROM orders o
        JOIN order_items oi
            ON o.order_id = oi.order_id
        JOIN products p
            ON oi.product_id = p.product_id
        GROUP BY o.order_id
    )
);


-- Q47. Find customers who have never placed an order
SELECT c.customer_id,
       c.customer_name
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id
WHERE o.order_id IS NULL;


-- Q48. Find the second highest product price
SELECT MAX(price) AS second_highest_price
FROM products
WHERE price < (
    SELECT MAX(price)
    FROM products
);


-- Q49. Find products priced higher than the average price of their category
SELECT p.product_id,
       p.product_name,
       p.price,
       p.category_id
FROM products p
WHERE p.price > (
    SELECT AVG(p2.price)
    FROM products p2
    WHERE p2.category_id = p.category_id
);


-- Q50. Find the customer who placed the most orders
SELECT c.customer_id,
       c.customer_name,
       COUNT(o.order_id) AS total_orders
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id,
         c.customer_name
ORDER BY total_orders DESC
FETCH FIRST 1 ROW ONLY;

-- ============================================
-- ADVANCED JOINS & SUBQUERIES
-- Q51 - Q75
-- ============================================

-- Q51. Find customers whose total revenue is greater than
-- the average customer revenue
SELECT c.customer_id,
       c.customer_name,
       SUM(p.price * oi.quantity) AS total_revenue
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id
GROUP BY c.customer_id, c.customer_name
HAVING SUM(p.price * oi.quantity) > (
    SELECT AVG(total_revenue)
    FROM (
        SELECT SUM(p2.price * oi2.quantity) AS total_revenue
        FROM customers c2
        JOIN orders o2
            ON c2.customer_id = o2.customer_id
        JOIN order_items oi2
            ON o2.order_id = oi2.order_id
        JOIN products p2
            ON oi2.product_id = p2.product_id
        GROUP BY c2.customer_id
    )
);


-- Q52. Find the product with the highest total quantity sold
SELECT p.product_id,
       p.product_name,
       SUM(oi.quantity) AS total_quantity
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_quantity DESC
FETCH FIRST 1 ROW ONLY;


-- Q53. Find the category with the highest total revenue
SELECT c.category_name,
       SUM(p.price * oi.quantity) AS total_revenue
FROM categories c
JOIN products p
    ON c.category_id = p.category_id
JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY c.category_name
ORDER BY total_revenue DESC
FETCH FIRST 1 ROW ONLY;


-- Q54. Find customers who purchased a Laptop
SELECT DISTINCT c.customer_id,
       c.customer_name
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id
WHERE p.product_name = 'Laptop';


-- Q55. Find customers who purchased products from Electronics
SELECT DISTINCT c.customer_id,
       c.customer_name
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id
JOIN categories ca
    ON p.category_id = ca.category_id
WHERE ca.category_name = 'Electronics';


-- Q56. Find the total number of products purchased by each customer
SELECT c.customer_id,
       c.customer_name,
       SUM(oi.quantity) AS total_products
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY c.customer_id, c.customer_name;


-- Q57. Find the customer who purchased the highest quantity of products
SELECT c.customer_id,
       c.customer_name,
       SUM(oi.quantity) AS total_quantity
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY c.customer_id, c.customer_name
ORDER BY total_quantity DESC
FETCH FIRST 1 ROW ONLY;


-- Q58. Find the number of different products purchased by each customer
SELECT c.customer_id,
       c.customer_name,
       COUNT(DISTINCT oi.product_id) AS different_products
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY c.customer_id, c.customer_name;


-- Q59. Find customers who purchased more than one different product
SELECT c.customer_id,
       c.customer_name,
       COUNT(DISTINCT oi.product_id) AS different_products
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY c.customer_id, c.customer_name
HAVING COUNT(DISTINCT oi.product_id) > 1;


-- Q60. Find the total revenue generated in each month
SELECT EXTRACT(MONTH FROM o.order_date) AS order_month,
       SUM(p.price * oi.quantity) AS monthly_revenue
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id
GROUP BY EXTRACT(MONTH FROM o.order_date)
ORDER BY order_month;


-- Q61. Find the number of orders placed in each month
SELECT EXTRACT(MONTH FROM order_date) AS order_month,
       COUNT(*) AS total_orders
FROM orders
GROUP BY EXTRACT(MONTH FROM order_date)
ORDER BY order_month;


-- Q62. Find the customer with the highest number of completed orders
SELECT c.customer_id,
       c.customer_name,
       COUNT(o.order_id) AS completed_orders
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
WHERE o.status = 'Completed'
GROUP BY c.customer_id, c.customer_name
ORDER BY completed_orders DESC
FETCH FIRST 1 ROW ONLY;


-- Q63. Find the total revenue from completed orders
SELECT SUM(p.price * oi.quantity) AS completed_revenue
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id
WHERE o.status = 'Completed';


-- Q64. Find the total revenue from shipped orders
SELECT SUM(p.price * oi.quantity) AS shipped_revenue
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id
WHERE o.status = 'Shipped';


-- Q65. Find customers who have both Completed and Shipped orders
SELECT c.customer_id,
       c.customer_name
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
HAVING COUNT(CASE WHEN o.status = 'Completed' THEN 1 END) > 0
   AND COUNT(CASE WHEN o.status = 'Shipped' THEN 1 END) > 0;


-- Q66. Find the product with the highest revenue
SELECT p.product_id,
       p.product_name,
       SUM(p.price * oi.quantity) AS total_revenue
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_revenue DESC
FETCH FIRST 1 ROW ONLY;


-- Q67. Find products that generated revenue greater than 10000
SELECT p.product_id,
       p.product_name,
       SUM(p.price * oi.quantity) AS total_revenue
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY p.product_id, p.product_name
HAVING SUM(p.price * oi.quantity) > 10000;


-- Q68. Find the average revenue per customer
SELECT AVG(total_revenue) AS average_customer_revenue
FROM (
    SELECT c.customer_id,
           SUM(p.price * oi.quantity) AS total_revenue
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    JOIN order_items oi
        ON o.order_id = oi.order_id
    JOIN products p
        ON oi.product_id = p.product_id
    GROUP BY c.customer_id
);


-- Q69. Find customers whose order count is above the average order count
SELECT c.customer_id,
       c.customer_name,
       COUNT(o.order_id) AS total_orders
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
HAVING COUNT(o.order_id) > (
    SELECT AVG(order_count)
    FROM (
        SELECT COUNT(*) AS order_count
        FROM orders
        GROUP BY customer_id
    )
);


-- Q70. Find the latest order date for each customer
SELECT c.customer_id,
       c.customer_name,
       MAX(o.order_date) AS latest_order_date
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name;


-- Q71. Find the first order date for each customer
SELECT c.customer_id,
       c.customer_name,
       MIN(o.order_date) AS first_order_date
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name;


-- Q72. Find customers whose latest order was placed after
-- March 1, 2026
SELECT c.customer_id,
       c.customer_name,
       MAX(o.order_date) AS latest_order_date
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
HAVING MAX(o.order_date) > DATE '2026-03-01';


-- Q73. Find the most expensive product in each category
SELECT c.category_name,
       p.product_name,
       p.price
FROM categories c
JOIN products p
    ON c.category_id = p.category_id
WHERE p.price = (
    SELECT MAX(p2.price)
    FROM products p2
    WHERE p2.category_id = p.category_id
);


-- Q74. Find customers who purchased the most expensive product
SELECT DISTINCT c.customer_id,
       c.customer_name
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id
WHERE p.price = (
    SELECT MAX(price)
    FROM products
);


-- Q75. Find the customer with the highest total revenue
SELECT c.customer_id,
       c.customer_name,
       SUM(p.price * oi.quantity) AS total_revenue,
       COUNT(DISTINCT o.order_id) AS total_orders
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id
GROUP BY c.customer_id, c.customer_name
ORDER BY total_revenue DESC
FETCH FIRST 1 ROW ONLY;
